stages:
  - test

variables:
  GIT_DEPTH: 3

before_script:
  - uname -a
  - lsb_release -a
  - cat /etc/os-release
  - mount
  - df -h
  - cat /proc/swaps
  - free -h
  - sudo apt-get -qq update
  - sudo apt-get install -y libtool libtool-bin automake autoconf libevent-dev libssl-dev libgcrypt-dev libkrb5-dev libpam0g-dev libdb-dev libtdb-dev libmysqlclient-dev libavahi-client-dev libacl1-dev libldap2-dev libcrack2-dev systemtap-sdt-dev libdbus-1-dev libdbus-glib-1-dev libglib2.0-dev

after_script:
  - mount
  - df -h
  - cat /proc/swaps
  - free -h

ubuntu1604:
  image: $CI_REGISTRY/netatalk-team/netatalk:latest
  stage: test
  script:
  - git clone https://gitlab.com/netatalk-team/netatalk.git
  - cd netatalk && ./bootstrap && ./configure && make -j && make check
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    when: on_failure
